### ISSUE TITLE
EMG Slides/Video

### ISSUE THREAD

**Issue by suyashcjoshi** [neurotech-berkeley/neurotech-course#4]
Hi,

Thanks for making this course publicly available on GItHub, I'm a hacker/maker and recently got into hacking around BCI and ordered BCI Kit from Open BCI, it came with EMG sensors and would love to learn more about EMG and how to use that. In your course outline, I noticed a section around that but content is missing. Could you please share/update content for EMG?

Thank you,
Suyash Joshi
Creative Technologist
San Francisco

**Comment by devennavani** [comment]
EMG content is on the way!
